### ISSUE TITLE
Coverage issue

### ISSUE THREAD

**Issue by kefniark** [AkifumiSato/esbuild-jest-transform#1]
Thanks for the work quite useful,

I've been trying to use jest with a esbuild project recently, and I tried few transformer out there without success.
* https://github.com/aelbore/esbuild-jest
* https://www.npmjs.com/package/jest-esbuild

yours seem to be the only one working, congrats 👍 

But I still have one problem, it properly run tests and report
![image](https://user-images.githubusercontent.com/4903529/116084017-4a063680-a6d8-11eb-911a-00e9bc057c0a.png)

But it doesnt seem to work with code coverage
![image](https://user-images.githubusercontent.com/4903529/116084132-6a35f580-a6d8-11eb-9eda-9e57df0fb1ae.png)

It's probably more related to Jest than this transformer, but just to ask, do you have any idea what can cause that ?

**Comment by AkifumiSato** [comment]
Thanks for the feedback!
I also tried it and got the same result.

> It's probably more related to Jest than this transformer, but just to ask, do you have any idea what can cause that ?

I'm sorry, I didn't understand why this happened, As you say, it's probably Jest's problem.

**Comment by AkifumiSato** [comment]
It seems that esbuild cannot be specified for Jest's coverageProvider.
https://jestjs.io/docs/cli#--coverageproviderprovider

**Comment by kefniark** [comment]
Thanks for the feedback and glad you can reproduce it too,

I will try older version of jest to see if the behavior was the same in the past, and I will open an issue on their repo.

Thanks
