### ISSUE TITLE
Provide options in jest config file

### ISSUE THREAD

**Issue by davityavryan** [AkifumiSato/esbuild-jest-transform#2]
Hey @AkifumiSato 

Nice package, helped a lot.
Any plans to give us ability to provide options in jest config like https://www.npmjs.com/package/esbuild-jest does?

This will be better IMO. currently it is required to have another (as you might know proper Jest config already requires a lot of setup files) config file specifically only for esbuild config.

**Comment by AkifumiSato** [comment]
@davityavryan I don't have any plans for that at the moment, but I'll add it if you implement it.
thanks

**Comment by AkifumiSato** [comment]
Released in `v1.1.0`
