### ISSUE TITLE
Allow running without a `jest.esbuild.js`

### ISSUE THREAD

**Issue by gustavopch** [AkifumiSato/esbuild-jest-transform#3]
Currently, `esbuild-jest-transform` crashes when `jest.esbuild.js` doesn't exist. So it must exist even if only to contain `module.exports = {}`. The problem is here:
https://github.com/AkifumiSato/esbuild-jest-transform/blob/ae425365a06dba3d357b72251f990de70c7071ae/index.ts#L7
I think it could use `{}` as the default config when that file doesn't exist.

**Comment by AkifumiSato** [comment]
@gustavopch Fixed in v1.0.8.
Thank you for pointing out!
