### ISSUE TITLE
Update peer deps to latest version of esbuild

### ISSUE THREAD

**Issue by httpete** [AkifumiSato/esbuild-jest-transform#6]
Hi, I am impressed by the simplicity of your plugin. But can you bump that peer dep to the latest?

**Comment by AkifumiSato** [comment]
Hi, I want to support the lower versions as well, so I want to keep it that way.
Is there any inconvenience if I don't update?

**Comment by allomov** [comment]
@AkifumiSato I also like the simplicity of this plugin. Thank you for the work!

Would it make sense to leave support of old versions to the older version of [esbuild-jest-transform](https://github.com/AkifumiSato/esbuild-jest-transform) and go with the newer versions with the new

**Comment by AkifumiSato** [comment]
@allomov Thank you for your advice!
I agree, so I have done the update work and released `v1.1.1`.
The `v1.1.1` requires esbuild latest version.

**Comment by allomov** [comment]
Yey! Thank you. It will work for me.
